[package]
name = "codewars-rs"
version = "0.1.0"
authors = ["Malhar Vora"]
edition = "2018"


[dependencies]
reqwest = {version = "0.10.8", features = ["blocking", "json"]}
serde = {version = "1.0.117", features = ["derive"]}
serde_json = "1.0"
